/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthPendingApprovalRouteImport } from './routes/auth/pending-approval'
import { Route as AuthRejectedRouteImport } from './routes/auth/rejected'
import { Route as AuthSuspendedRouteImport } from './routes/auth/suspended'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardPromotionsRouteImport } from './routes/dashboard/promotions'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard/revenue'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSupportRouteImport } from './routes/dashboard/support'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password/verify'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects.$projectId'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects.new'
import { Route as DashboardPromotionsIndexRouteImport } from './routes/dashboard/promotions/index'
import { Route as DashboardPromotionsPromotionIdRouteImport } from './routes/dashboard/promotions.$promotionId'
import { Route as DashboardRevenueIndexRouteImport } from './routes/dashboard/revenue/index'
import { Route as DashboardRevenueAnalyticsRouteImport } from './routes/dashboard/revenue/analytics'
import { Route as DashboardRevenuePayoutsRouteImport } from './routes/dashboard/revenue/payouts'
import { Route as DashboardRevenueSettingsRouteImport } from './routes/dashboard/revenue/settings'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsArchiveRouteImport } from './routes/dashboard/settings/archive'
import { Route as DashboardSettingsEarningsRouteImport } from './routes/dashboard/settings/earnings'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardSettingsPreferencesRouteImport } from './routes/dashboard/settings/preferences'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsStudioRouteImport } from './routes/dashboard/settings/studio'
import { Route as DashboardSettingsTeamRouteImport } from './routes/dashboard/settings/team'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/dashboard/projects.$projectId/index'
import { Route as DashboardProjectsProjectIdAnalyticsRouteImport } from './routes/dashboard/projects.$projectId/analytics'
import { Route as DashboardProjectsProjectIdEpisodesRouteImport } from './routes/dashboard/projects.$projectId/episodes'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard/projects.$projectId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingApprovalRoute = AuthPendingApprovalRouteImport.update({
  id: '/auth/pending-approval',
  path: '/auth/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRejectedRoute = AuthRejectedRouteImport.update({
  id: '/auth/rejected',
  path: '/auth/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuspendedRoute = AuthSuspendedRouteImport.update({
  id: '/auth/suspended',
  path: '/auth/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPromotionsRoute = DashboardPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardPromotionsIndexRoute =
  DashboardPromotionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardPromotionsRoute,
  } as any)
const DashboardPromotionsPromotionIdRoute =
  DashboardPromotionsPromotionIdRouteImport.update({
    id: '/$promotionId',
    path: '/$promotionId',
    getParentRoute: () => DashboardPromotionsRoute,
  } as any)
const DashboardRevenueIndexRoute = DashboardRevenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRevenueRoute,
} as any)
const DashboardRevenueAnalyticsRoute =
  DashboardRevenueAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardRevenueRoute,
  } as any)
const DashboardRevenuePayoutsRoute = DashboardRevenuePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRevenueRoute,
} as any)
const DashboardRevenueSettingsRoute =
  DashboardRevenueSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardRevenueRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsArchiveRoute =
  DashboardSettingsArchiveRouteImport.update({
    id: '/archive',
    path: '/archive',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsEarningsRoute =
  DashboardSettingsEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsStudioRoute = DashboardSettingsStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdAnalyticsRoute =
  DashboardProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEpisodesRoute =
  DashboardProjectsProjectIdEpisodesRouteImport.update({
    id: '/episodes',
    path: '/episodes',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/rejected': typeof AuthRejectedRoute
  '/auth/suspended': typeof AuthSuspendedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/promotions': typeof DashboardPromotionsRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/support': typeof DashboardSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/promotions/$promotionId': typeof DashboardPromotionsPromotionIdRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/archive': typeof DashboardSettingsArchiveRoute
  '/dashboard/settings/earnings': typeof DashboardSettingsEarningsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/promotions/': typeof DashboardPromotionsIndexRoute
  '/dashboard/revenue/': typeof DashboardRevenueIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/rejected': typeof AuthRejectedRoute
  '/auth/suspended': typeof AuthSuspendedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/promotions/$promotionId': typeof DashboardPromotionsPromotionIdRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/archive': typeof DashboardSettingsArchiveRoute
  '/dashboard/settings/earnings': typeof DashboardSettingsEarningsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/promotions': typeof DashboardPromotionsIndexRoute
  '/dashboard/revenue': typeof DashboardRevenueIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/rejected': typeof AuthRejectedRoute
  '/auth/suspended': typeof AuthSuspendedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/promotions': typeof DashboardPromotionsRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/support': typeof DashboardSupportRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/promotions/$promotionId': typeof DashboardPromotionsPromotionIdRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/archive': typeof DashboardSettingsArchiveRoute
  '/dashboard/settings/earnings': typeof DashboardSettingsEarningsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/promotions/': typeof DashboardPromotionsIndexRoute
  '/dashboard/revenue/': typeof DashboardRevenueIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/auth/pending-approval'
    | '/auth/rejected'
    | '/auth/suspended'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/promotions'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/forgot-password/verify'
    | '/dashboard/'
    | '/forgot-password/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/promotions/$promotionId'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/archive'
    | '/dashboard/settings/earnings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/settings/team'
    | '/dashboard/projects/'
    | '/dashboard/promotions/'
    | '/dashboard/revenue/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/auth/pending-approval'
    | '/auth/rejected'
    | '/auth/suspended'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/support'
    | '/forgot-password/verify'
    | '/dashboard'
    | '/forgot-password'
    | '/dashboard/projects/new'
    | '/dashboard/promotions/$promotionId'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/archive'
    | '/dashboard/settings/earnings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/settings/team'
    | '/dashboard/projects'
    | '/dashboard/promotions'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/verify-email'
    | '/auth/pending-approval'
    | '/auth/rejected'
    | '/auth/suspended'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/projects'
    | '/dashboard/promotions'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/forgot-password/verify'
    | '/dashboard/'
    | '/forgot-password/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/promotions/$promotionId'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/archive'
    | '/dashboard/settings/earnings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/settings/team'
    | '/dashboard/projects/'
    | '/dashboard/promotions/'
    | '/dashboard/revenue/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthPendingApprovalRoute: typeof AuthPendingApprovalRoute
  AuthRejectedRoute: typeof AuthRejectedRoute
  AuthSuspendedRoute: typeof AuthSuspendedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending-approval': {
      id: '/auth/pending-approval'
      path: '/auth/pending-approval'
      fullPath: '/auth/pending-approval'
      preLoaderRoute: typeof AuthPendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/rejected': {
      id: '/auth/rejected'
      path: '/auth/rejected'
      fullPath: '/auth/rejected'
      preLoaderRoute: typeof AuthRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/suspended': {
      id: '/auth/suspended'
      path: '/auth/suspended'
      fullPath: '/auth/suspended'
      preLoaderRoute: typeof AuthSuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/promotions': {
      id: '/dashboard/promotions'
      path: '/promotions'
      fullPath: '/dashboard/promotions'
      preLoaderRoute: typeof DashboardPromotionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/promotions/': {
      id: '/dashboard/promotions/'
      path: '/'
      fullPath: '/dashboard/promotions/'
      preLoaderRoute: typeof DashboardPromotionsIndexRouteImport
      parentRoute: typeof DashboardPromotionsRoute
    }
    '/dashboard/promotions/$promotionId': {
      id: '/dashboard/promotions/$promotionId'
      path: '/$promotionId'
      fullPath: '/dashboard/promotions/$promotionId'
      preLoaderRoute: typeof DashboardPromotionsPromotionIdRouteImport
      parentRoute: typeof DashboardPromotionsRoute
    }
    '/dashboard/revenue/': {
      id: '/dashboard/revenue/'
      path: '/'
      fullPath: '/dashboard/revenue/'
      preLoaderRoute: typeof DashboardRevenueIndexRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/revenue/analytics': {
      id: '/dashboard/revenue/analytics'
      path: '/analytics'
      fullPath: '/dashboard/revenue/analytics'
      preLoaderRoute: typeof DashboardRevenueAnalyticsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/revenue/payouts': {
      id: '/dashboard/revenue/payouts'
      path: '/payouts'
      fullPath: '/dashboard/revenue/payouts'
      preLoaderRoute: typeof DashboardRevenuePayoutsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/revenue/settings': {
      id: '/dashboard/revenue/settings'
      path: '/settings'
      fullPath: '/dashboard/revenue/settings'
      preLoaderRoute: typeof DashboardRevenueSettingsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/archive': {
      id: '/dashboard/settings/archive'
      path: '/archive'
      fullPath: '/dashboard/settings/archive'
      preLoaderRoute: typeof DashboardSettingsArchiveRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/earnings': {
      id: '/dashboard/settings/earnings'
      path: '/earnings'
      fullPath: '/dashboard/settings/earnings'
      preLoaderRoute: typeof DashboardSettingsEarningsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/preferences': {
      id: '/dashboard/settings/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/preferences'
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/studio': {
      id: '/dashboard/settings/studio'
      path: '/studio'
      fullPath: '/dashboard/settings/studio'
      preLoaderRoute: typeof DashboardSettingsStudioRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/team': {
      id: '/dashboard/settings/team'
      path: '/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/analytics': {
      id: '/dashboard/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/projects/$projectId/analytics'
      preLoaderRoute: typeof DashboardProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/episodes': {
      id: '/dashboard/projects/$projectId/episodes'
      path: '/episodes'
      fullPath: '/dashboard/projects/$projectId/episodes'
      preLoaderRoute: typeof DashboardProjectsProjectIdEpisodesRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdAnalyticsRoute: typeof DashboardProjectsProjectIdAnalyticsRoute
  DashboardProjectsProjectIdEpisodesRoute: typeof DashboardProjectsProjectIdEpisodesRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdAnalyticsRoute:
      DashboardProjectsProjectIdAnalyticsRoute,
    DashboardProjectsProjectIdEpisodesRoute:
      DashboardProjectsProjectIdEpisodesRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardPromotionsRouteChildren {
  DashboardPromotionsPromotionIdRoute: typeof DashboardPromotionsPromotionIdRoute
  DashboardPromotionsIndexRoute: typeof DashboardPromotionsIndexRoute
}

const DashboardPromotionsRouteChildren: DashboardPromotionsRouteChildren = {
  DashboardPromotionsPromotionIdRoute: DashboardPromotionsPromotionIdRoute,
  DashboardPromotionsIndexRoute: DashboardPromotionsIndexRoute,
}

const DashboardPromotionsRouteWithChildren =
  DashboardPromotionsRoute._addFileChildren(DashboardPromotionsRouteChildren)

interface DashboardRevenueRouteChildren {
  DashboardRevenueAnalyticsRoute: typeof DashboardRevenueAnalyticsRoute
  DashboardRevenuePayoutsRoute: typeof DashboardRevenuePayoutsRoute
  DashboardRevenueSettingsRoute: typeof DashboardRevenueSettingsRoute
  DashboardRevenueIndexRoute: typeof DashboardRevenueIndexRoute
}

const DashboardRevenueRouteChildren: DashboardRevenueRouteChildren = {
  DashboardRevenueAnalyticsRoute: DashboardRevenueAnalyticsRoute,
  DashboardRevenuePayoutsRoute: DashboardRevenuePayoutsRoute,
  DashboardRevenueSettingsRoute: DashboardRevenueSettingsRoute,
  DashboardRevenueIndexRoute: DashboardRevenueIndexRoute,
}

const DashboardRevenueRouteWithChildren =
  DashboardRevenueRoute._addFileChildren(DashboardRevenueRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsArchiveRoute: typeof DashboardSettingsArchiveRoute
  DashboardSettingsEarningsRoute: typeof DashboardSettingsEarningsRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsStudioRoute: typeof DashboardSettingsStudioRoute
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsArchiveRoute: DashboardSettingsArchiveRoute,
  DashboardSettingsEarningsRoute: DashboardSettingsEarningsRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsStudioRoute: DashboardSettingsStudioRoute,
  DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardPromotionsRoute: typeof DashboardPromotionsRouteWithChildren
  DashboardRevenueRoute: typeof DashboardRevenueRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardPromotionsRoute: DashboardPromotionsRouteWithChildren,
  DashboardRevenueRoute: DashboardRevenueRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthPendingApprovalRoute: AuthPendingApprovalRoute,
  AuthRejectedRoute: AuthRejectedRoute,
  AuthSuspendedRoute: AuthSuspendedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
