/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard/revenue'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardRevenueIndexRouteImport } from './routes/dashboard/revenue/index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard/projects/index'
import { Route as DashboardSettingsStudioRouteImport } from './routes/dashboard/settings/studio'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsPreferencesRouteImport } from './routes/dashboard/settings/preferences'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardRevenueSettingsRouteImport } from './routes/dashboard/revenue/settings'
import { Route as DashboardRevenuePayoutsRouteImport } from './routes/dashboard/revenue/payouts'
import { Route as DashboardRevenueAnalyticsRouteImport } from './routes/dashboard/revenue/analytics'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard/projects.new'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard/projects.$projectId'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/dashboard/projects.$projectId/index'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/dashboard/projects.$projectId/settings'
import { Route as DashboardProjectsProjectIdEpisodesRouteImport } from './routes/dashboard/projects.$projectId/episodes'
import { Route as DashboardProjectsProjectIdAnalyticsRouteImport } from './routes/dashboard/projects.$projectId/analytics'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardRevenueIndexRoute = DashboardRevenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRevenueRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardSettingsStudioRoute = DashboardSettingsStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsPreferencesRoute =
  DashboardSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardRevenueSettingsRoute =
  DashboardRevenueSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardRevenueRoute,
  } as any)
const DashboardRevenuePayoutsRoute = DashboardRevenuePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRevenueRoute,
} as any)
const DashboardRevenueAnalyticsRoute =
  DashboardRevenueAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardRevenueRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdEpisodesRoute =
  DashboardProjectsProjectIdEpisodesRouteImport.update({
    id: '/episodes',
    path: '/episodes',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdAnalyticsRoute =
  DashboardProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/revenue/': typeof DashboardRevenueIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/revenue': typeof DashboardRevenueIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/revenue/analytics': typeof DashboardRevenueAnalyticsRoute
  '/dashboard/revenue/payouts': typeof DashboardRevenuePayoutsRoute
  '/dashboard/revenue/settings': typeof DashboardRevenueSettingsRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/preferences': typeof DashboardSettingsPreferencesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/studio': typeof DashboardSettingsStudioRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/revenue/': typeof DashboardRevenueIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/projects/$projectId/analytics': typeof DashboardProjectsProjectIdAnalyticsRoute
  '/dashboard/projects/$projectId/episodes': typeof DashboardProjectsProjectIdEpisodesRoute
  '/dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/projects'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/projects/'
    | '/dashboard/revenue/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/projects/new'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/projects'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/analytics'
    | '/dashboard/projects'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/revenue/analytics'
    | '/dashboard/revenue/payouts'
    | '/dashboard/revenue/settings'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/preferences'
    | '/dashboard/settings/security'
    | '/dashboard/settings/studio'
    | '/dashboard/projects/'
    | '/dashboard/revenue/'
    | '/dashboard/settings/'
    | '/dashboard/projects/$projectId/analytics'
    | '/dashboard/projects/$projectId/episodes'
    | '/dashboard/projects/$projectId/settings'
    | '/dashboard/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/revenue/': {
      id: '/dashboard/revenue/'
      path: '/'
      fullPath: '/dashboard/revenue/'
      preLoaderRoute: typeof DashboardRevenueIndexRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/settings/studio': {
      id: '/dashboard/settings/studio'
      path: '/studio'
      fullPath: '/dashboard/settings/studio'
      preLoaderRoute: typeof DashboardSettingsStudioRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/preferences': {
      id: '/dashboard/settings/preferences'
      path: '/preferences'
      fullPath: '/dashboard/settings/preferences'
      preLoaderRoute: typeof DashboardSettingsPreferencesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/revenue/settings': {
      id: '/dashboard/revenue/settings'
      path: '/settings'
      fullPath: '/dashboard/revenue/settings'
      preLoaderRoute: typeof DashboardRevenueSettingsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/revenue/payouts': {
      id: '/dashboard/revenue/payouts'
      path: '/payouts'
      fullPath: '/dashboard/revenue/payouts'
      preLoaderRoute: typeof DashboardRevenuePayoutsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/revenue/analytics': {
      id: '/dashboard/revenue/analytics'
      path: '/analytics'
      fullPath: '/dashboard/revenue/analytics'
      preLoaderRoute: typeof DashboardRevenueAnalyticsRouteImport
      parentRoute: typeof DashboardRevenueRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/$projectId/': {
      id: '/dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/dashboard/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/settings': {
      id: '/dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/dashboard/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/episodes': {
      id: '/dashboard/projects/$projectId/episodes'
      path: '/episodes'
      fullPath: '/dashboard/projects/$projectId/episodes'
      preLoaderRoute: typeof DashboardProjectsProjectIdEpisodesRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/dashboard/projects/$projectId/analytics': {
      id: '/dashboard/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/dashboard/projects/$projectId/analytics'
      preLoaderRoute: typeof DashboardProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
  }
}

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdAnalyticsRoute: typeof DashboardProjectsProjectIdAnalyticsRoute
  DashboardProjectsProjectIdEpisodesRoute: typeof DashboardProjectsProjectIdEpisodesRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdAnalyticsRoute:
      DashboardProjectsProjectIdAnalyticsRoute,
    DashboardProjectsProjectIdEpisodesRoute:
      DashboardProjectsProjectIdEpisodesRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRevenueRouteChildren {
  DashboardRevenueAnalyticsRoute: typeof DashboardRevenueAnalyticsRoute
  DashboardRevenuePayoutsRoute: typeof DashboardRevenuePayoutsRoute
  DashboardRevenueSettingsRoute: typeof DashboardRevenueSettingsRoute
  DashboardRevenueIndexRoute: typeof DashboardRevenueIndexRoute
}

const DashboardRevenueRouteChildren: DashboardRevenueRouteChildren = {
  DashboardRevenueAnalyticsRoute: DashboardRevenueAnalyticsRoute,
  DashboardRevenuePayoutsRoute: DashboardRevenuePayoutsRoute,
  DashboardRevenueSettingsRoute: DashboardRevenueSettingsRoute,
  DashboardRevenueIndexRoute: DashboardRevenueIndexRoute,
}

const DashboardRevenueRouteWithChildren =
  DashboardRevenueRoute._addFileChildren(DashboardRevenueRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsPreferencesRoute: typeof DashboardSettingsPreferencesRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsStudioRoute: typeof DashboardSettingsStudioRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsPreferencesRoute: DashboardSettingsPreferencesRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsStudioRoute: DashboardSettingsStudioRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardRevenueRoute: typeof DashboardRevenueRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardRevenueRoute: DashboardRevenueRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
